### ISSUE TITLE
Doubt: Compute Similarity between items

### ISSUE THREAD

**Issue by tagline** [cloudera/oryx#122]
Hi!

There's a way to compute similarity between all items in a dataset and obtain a text file result?
I would not like to ask in the webpage (Oryx Serving Layer - http://localhost:8093/) for each item..

Do you have a kind of feature for that? 

Thanks in advance!

**Comment by srowen** [comment]
(You can ask questions on the mailing list: https://groups.google.com/a/cloudera.org/forum/#!forum/oryx-user )
This version of the project is no longer developed. You probably want to look at https://github.com/OryxProject/oryx/

There isn't a method for all-pairs similarity since that's not really something you'd do interactively.
